name: Publish to npm

on:
  push:
    branches:
      - publish-npm #TODO REMOVE
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: library
    steps:
      - uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          working_directory: library
          branches: |
            [
              'main', 
              'publish-npm',
            ]
    env:
      GITHUB_TOKEN: ${{ secrets.HOWMUCHBOT_GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.HOWMUCHBOT_NPM_TOKEN }}
