name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: library
    steps:
      - uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.19.4"
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: library
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          working_directory: library/dist/published
          branches: |
            [
              'main',
            ]
      - name: Trigger website update
        run: |
          curl -XPOST -u "howmuchbot:${{secrets.HOWMUCHBOT_GH_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/howmuchgreen/website/dispatches --data '{"event_type": "upgrade-library"}'
    env:
      GITHUB_TOKEN: ${{ secrets.HOWMUCHBOT_GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.HOWMUCHBOT_NPM_TOKEN }}
